repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: check-added-large-files
        args: ['--maxkb=500']


-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
    -   id: isort

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.13.3
    hooks:
    -   id: ruff
        args: [--fix]
