"""Render card dicts to PDF via Jinja2 + WeasyPrint."""

import json
import random
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape
from joblib import Parallel, delayed
from weasyprint import HTML

from lib.font_metadata import FONT_SPECS
from lib.models import Config, SectionTheme, VisualIdentity
from lib.registry import get_all_schema_classes, get_templates_for_schema
from schemas._base import Schema
from tools.generate_images import get_diagram_image_base64, get_image_base64

_TEMPLATES_DIR = Path(__file__).parent.parent / "templates"


def build_google_fonts_url(vi: VisualIdentity) -> str:
    """
    Build a Google Fonts CSS2 URL for the visual identity's fonts.

    Uses FONT_SPECS (generated by scripts/generate_font_metadata.py) for correct
    axis ranges per font. Falls back to bare family name (400 only) for unknown fonts.
    Deduplicates when title_font and body_font are the same.
    """
    params: list[str] = []
    seen: set[str] = set()
    for font_name in [vi.title_font, vi.body_font]:
        if not font_name or font_name in seen:
            continue
        seen.add(font_name)
        spec = FONT_SPECS.get(font_name, font_name.replace(" ", "+"))
        params.append(spec)
    family_str = "&family=".join(params)
    return f"https://fonts.googleapis.com/css2?family={family_str}&display=swap"


# Predefined visual identities for testing and quality control
PREDEFINED_STYLES = {
    "classic": VisualIdentity(
        description="Quiet luxury editorial design with serif typography",
        title_font="EB Garamond",
        body_font="Lora",
        section_themes=[
            SectionTheme(main_color="#1a1a1a", dark_color="#000000", accent_color="#FF6B6B"),
        ],
    ),
    "minimal": VisualIdentity(
        description="Minimalist monospace with bold headers",
        title_font="IBM Plex Mono",
        body_font="IBM Plex Mono",
        section_themes=[
            SectionTheme(main_color="#000000", dark_color="#000000", accent_color="#0066CC"),
        ],
    ),
    "contemporary": VisualIdentity(
        description="Contemporary split layout with accent bar",
        title_font="Inter",
        body_font="Inter",
        section_themes=[
            SectionTheme(main_color="#2563EB", dark_color="#1E40AF", accent_color="#F59E0B"),
        ],
    ),
}


def render_card_to_pdf(
    card: dict,
    template_name: str,
    output_dir: Path,
    images_dir: Path,
    *,
    card_index: int,
    visual_identity: dict | VisualIdentity | None = None,
) -> Path:
    """
    Render a single card dict with the named Jinja2 template to a PDF file.

    - Loads the template from src/templates/.
    - Exposes get_image(prompt, width, height) callable to the template.
    - Passes visual_identity (fonts, colors) to template for styling.
    - Assumes all cards render at A6 size (scaling happens at PDF merge stage).
    - Writes output to `output_dir/card-{card_index}.pdf`.
    - Returns the path to the generated PDF.
    """
    env = Environment(
        loader=FileSystemLoader(str(_TEMPLATES_DIR)),
        autoescape=select_autoescape(["html", "xml"]),
    )
    template = env.get_template(template_name)

    # Prepare template variables
    template_vars = dict(card)

    # Expose image generation functions to templates
    def get_image(prompt: str, width: int = 768, height: int = 512) -> str | None:
        """Generate or retrieve a Runware cached image as base64. Called from Jinja2 templates."""
        return get_image_base64(prompt, images_dir, size=(height, width))

    def get_diagram_image(prompt: str, width: int = 256, height: int = 256) -> str | None:
        """Generate or retrieve a Gemini Flash diagram image as base64. Called from Jinja2 templates."""
        return get_diagram_image_base64(prompt, images_dir)

    # Pass visual_identity as-is (not flattened); card fields override if names collide
    if visual_identity is not None:
        vi_obj = (
            visual_identity
            if isinstance(visual_identity, VisualIdentity)
            else VisualIdentity.model_validate(visual_identity)
        )
        template_vars["visual_identity"] = vi_obj.model_dump()
        template_vars["google_fonts_url"] = build_google_fonts_url(vi_obj)

    template_vars["get_image"] = get_image
    template_vars["get_diagram_image"] = get_diagram_image

    rendered_html = template.render(**template_vars)

    pdf_path = output_dir / f"card-{card_index}.pdf"
    HTML(string=rendered_html, base_url=str(_TEMPLATES_DIR)).write_pdf(pdf_path)
    return pdf_path


def cards_json_to_pdfs(
    cards_json_path: Path,
    output_dir: Path,
    config: Config,
    images_dir: Path,
    *,
    n_jobs: int = -1,
) -> list[Path]:
    """
    Render all cards in bbGame.cards to individual PDF files.

    Selects a template for each card (randomly from schema.templates, or as
    specified in the card dict). Runs in parallel via joblib when n_jobs != 1.

    Returns the list of generated PDF paths, in card order.
    """
    from lib.models import BBGame

    output_dir.mkdir(parents=True, exist_ok=True)
    game_data = json.loads(cards_json_path.read_text(encoding="utf-8"))
    game = BBGame.model_validate(game_data)
    cards = [c.model_dump() for c in game.cards]

    # Build map: card type string → schema class
    schema_by_type: dict[str, type[Schema]] = {}
    for cls in get_all_schema_classes():
        type_field = cls.model_fields.get("type")
        if type_field and type_field.default:
            schema_by_type[type_field.default] = cls

    def _visual_identity_for_card(card: dict) -> VisualIdentity:
        """Return the VisualIdentity for this card, with section theme applied."""
        vi = game.visual_identity
        section = card.get("section", 0) or 0
        themes = vi.section_themes
        theme = themes[section] if 0 <= section < len(themes) else SectionTheme()
        # Create a new VisualIdentity with the section-specific theme merged in
        return VisualIdentity(
            description=vi.description,
            title_font=vi.title_font,
            body_font=vi.body_font,
            section_themes=[theme],  # Only pass the relevant theme
        )

    def _resolve_template(card: dict) -> str:
        if "template" in card:
            return card["template"]
        card_type = card.get("type", "")
        schema_cls = schema_by_type.get(card_type)
        if schema_cls:
            options = get_templates_for_schema(schema_cls)
            if options:
                return random.choice(options).name
        raise ValueError(f"No template found for card type {card_type!r}")

    tasks = [
        (i, card, _resolve_template(card), _visual_identity_for_card(card))
        for i, card in enumerate(cards)
    ]

    results: list[Path] = Parallel(n_jobs=n_jobs)(
        delayed(render_card_to_pdf)(
            card,
            template_name,
            output_dir,
            images_dir,
            card_index=i,
            visual_identity=vi,
        )
        for i, card, template_name, vi in tasks
    )
    return results
