"""Render card dicts to PDF via Jinja2 + WeasyPrint."""

import json
import logging
import random
from dataclasses import dataclass
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape
from joblib import Parallel, delayed
from weasyprint import HTML

from lib.constants import TEMPLATES_DIR
from lib.font_cache import fetch_and_cache_font_awesome, fetch_and_cache_fonts
from lib.font_metadata import FONT_SPECS
from lib.models import SectionTheme, VisualIdentity
from lib.registry import get_all_schema_classes, get_templates_for_schema
from schemas._base import Schema
from tools.generate_images import get_diagram_image_base64, get_image_base64


def build_google_fonts_url(
    vi: VisualIdentity,
    extra_fonts: list[str] | None = None,
) -> str:
    """
    Build a Google Fonts CSS2 URL for the visual identity's fonts.

    Uses FONT_SPECS (generated by scripts/generate_font_metadata.py) for correct
    axis ranges per font. Falls back to bare family name (400 only) for unknown fonts.
    Deduplicates when title_font and body_font are the same.
    extra_fonts: additional font families (e.g. ["EB Garamond"] for definition-lexicon).
    """
    params: list[str] = []
    seen: set[str] = set()
    for font_name in [vi.title_font, vi.body_font] + (extra_fonts or []):
        if not font_name or font_name in seen:
            continue
        seen.add(font_name)
        spec = FONT_SPECS.get(font_name, font_name.replace(" ", "+"))
        params.append(spec)
    family_str = "&family=".join(params)
    return f"https://fonts.googleapis.com/css2?family={family_str}&display=swap"


# Warnings from WeasyPrint parsing external CDN CSS (Google Fonts, Font Awesome).
# Their stylesheets use modern CSS (text-rendering, @media prefers-reduced-motion, @keyframes)
# that WeasyPrint's parser doesn't fully support. Output is fine; we filter these out.
# DON'T ADD anything here by default. Especially if the warning comes from one of the templates: we're likely using an unsupported feature of WeasyPrint.
HARMLESS_CSS_PATTERNS = (
    "Ignored `text-rendering:auto`",
    "Expected a media type, got",
    "Invalid media type",
    "Unknown rule <AtRule @keyframes",
)


def is_harmless_weasyprint_warning(msg: str) -> bool:
    """Return True if the WeasyPrint warning is known and harmless."""
    return any(p in msg for p in HARMLESS_CSS_PATTERNS)


@dataclass
class RenderResult:
    """Result of rendering one (card_type, template) combination."""

    card_type: str
    template_name: str
    pdf_path: Path
    warnings: list[str]


class LogCapture(logging.Handler):
    """Capture log records for inspection."""

    def __init__(self) -> None:
        super().__init__()
        self.records: list[logging.LogRecord] = []

    def emit(self, record: logging.LogRecord) -> None:
        self.records.append(record)


def render_one_template(
    card: dict,
    card_type: str,
    template_name: str,
    template_stem: str,
    output_dir: Path,
    images_dir: Path,
    visual_identity: dict,
) -> RenderResult:
    """Render one (card_type, template) and return result with captured warnings."""
    subdir = output_dir / f"{card_type}_{template_stem}"
    subdir.mkdir(parents=True, exist_ok=True)
    capture = LogCapture()
    wp_logger = logging.getLogger("weasyprint")
    wp_logger.addHandler(capture)
    try:
        pdf_path = render_card_to_pdf(
            card,
            template_name,
            subdir,
            images_dir,
            card_index=0,
            visual_identity=visual_identity,
        )
        warnings = [
            r.getMessage()
            for r in capture.records
            if r.levelno >= logging.WARNING and not is_harmless_weasyprint_warning(r.getMessage())
        ]
        return RenderResult(
            card_type=card_type,
            template_name=template_name,
            pdf_path=pdf_path,
            warnings=warnings,
        )
    finally:
        wp_logger.removeHandler(capture)


def render_all_templates(
    output_dir: Path,
    images_dir: Path,
    visual_identity: dict,
    example_cards: dict[str, dict] | None = None,
    n_jobs: int = -1,
) -> list[RenderResult]:
    """
    Render every (card_type, template) combination with example cards.

    Captures WeasyPrint logs and returns both output paths and non-harmless warnings.
    Uses joblib for parallel execution when n_jobs != 1.
    """
    from lib.example_cards import build_example_cards

    cards = example_cards if example_cards is not None else build_example_cards()
    output_dir.mkdir(parents=True, exist_ok=True)
    images_dir.mkdir(parents=True, exist_ok=True)
    vi = visual_identity

    tasks: list[tuple] = []
    for cls in get_all_schema_classes():
        type_field = cls.model_fields.get("type")
        card_type = type_field.default if type_field else "unknown"
        card = cards.get(card_type)
        if card is None:
            continue
        for template_path in get_templates_for_schema(cls):
            tasks.append(
                (
                    card,
                    card_type,
                    template_path.name,
                    template_path.stem,
                    output_dir,
                    images_dir,
                    vi,
                )
            )

    if n_jobs == 1:
        return [render_one_template(*t) for t in tasks]
    return list(
        Parallel(n_jobs=n_jobs, backend="threading")(
            delayed(render_one_template)(*t) for t in tasks
        )
    )


# Predefined visual identities for testing and quality control
PREDEFINED_STYLES = {
    "classic": VisualIdentity(
        description="Quiet luxury editorial design with serif typography",
        title_font="EB Garamond",
        body_font="Lora",
        section_themes=[
            SectionTheme(main_color="#1a1a1a", dark_color="#000000", accent_color="#FF6B6B"),
        ],
    ),
    "minimal": VisualIdentity(
        description="Minimalist monospace with bold headers",
        title_font="IBM Plex Mono",
        body_font="IBM Plex Mono",
        section_themes=[
            SectionTheme(main_color="#000000", dark_color="#000000", accent_color="#0066CC"),
        ],
    ),
    "contemporary": VisualIdentity(
        description="Contemporary split layout with accent bar",
        title_font="Inter",
        body_font="Inter",
        section_themes=[
            SectionTheme(main_color="#2563EB", dark_color="#1E40AF", accent_color="#F59E0B"),
        ],
    ),
}


def render_card_to_html(
    card: dict,
    template_name: str,
    images_dir: Path,
    *,
    visual_identity: dict | VisualIdentity,
    runware_model: str | None = None,
    force_regen_images: bool = False,
) -> str:
    """Render a single card dict with the named Jinja2 template, returning the HTML string."""
    vi_obj = (
        visual_identity
        if isinstance(visual_identity, VisualIdentity)
        else VisualIdentity.model_validate(visual_identity)
    )
    font_face_css = fetch_and_cache_fonts(
        build_google_fonts_url(vi_obj, extra_fonts=["EB Garamond"])
    )
    font_awesome_css = fetch_and_cache_font_awesome()

    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=select_autoescape(["html", "xml"]),
    )
    template = env.get_template(template_name)

    template_vars = dict(card)

    def get_image(prompt: str, width: int = 768, height: int = 512) -> str | None:
        return get_image_base64(
            prompt,
            images_dir,
            size=(height, width),
            model=runware_model,
            force_regen=force_regen_images,
        )

    def get_diagram_image(prompt: str, width: int = 400, height: int = 300) -> str | None:
        return get_diagram_image_base64(prompt, images_dir, size=(width, height))

    template_vars["visual_identity"] = vi_obj.model_dump()
    template_vars["font_face_css"] = font_face_css
    template_vars["font_awesome_css"] = font_awesome_css
    template_vars["get_image"] = get_image
    template_vars["get_diagram_image"] = get_diagram_image

    return template.render(**template_vars)


def render_card_to_pdf(
    card: dict,
    template_name: str,
    output_dir: Path,
    images_dir: Path,
    *,
    card_index: int,
    visual_identity: dict | VisualIdentity,
    runware_model: str | None = None,
    force_regen_images: bool = False,
) -> Path:
    """
    Render a single card dict with the named Jinja2 template to a PDF file.

    - Renders to HTML via render_card_to_html, then converts with WeasyPrint.
    - Assumes all cards render at A6 size (scaling happens at PDF merge stage).
    - Writes output to `output_dir/card-{card_index}.pdf`.
    - Returns the path to the generated PDF.
    """
    rendered_html = render_card_to_html(
        card,
        template_name,
        images_dir,
        visual_identity=visual_identity,
        runware_model=runware_model,
        force_regen_images=force_regen_images,
    )

    pdf_path = output_dir / f"card-{card_index}.pdf"
    HTML(string=rendered_html, base_url=str(TEMPLATES_DIR)).write_pdf(pdf_path)
    return pdf_path


def cards_json_to_pdfs(
    cards_json_path: Path,
    output_dir: Path,
    images_dir: Path,
    *,
    runware_model: str | None = None,
    force_regen_images: bool = False,
    n_jobs: int = -1,
) -> list[Path]:
    """
    Render all cards in bbGame.cards to individual PDF files.

    Selects a template for each card (randomly from schema.templates, or as
    specified in the card dict). Runs in parallel via joblib when n_jobs != 1.

    Returns the list of generated PDF paths, in card order.
    """
    from lib.models import BBGame

    output_dir.mkdir(parents=True, exist_ok=True)
    game_data = json.loads(cards_json_path.read_text(encoding="utf-8"))
    game = BBGame.model_validate(game_data)
    cards = [c.model_dump() for c in game.cards]

    # Build map: card type string → schema class
    schema_by_type: dict[str, type[Schema]] = {}
    for cls in get_all_schema_classes():
        type_field = cls.model_fields.get("type")
        if type_field and type_field.default:
            schema_by_type[type_field.default] = cls

    def _visual_identity_for_card(card: dict) -> VisualIdentity:
        """Return the VisualIdentity for this card, with section theme applied."""
        vi = game.visual_identity
        section = card.get("section", 0) or 0
        themes = vi.section_themes
        theme = themes[section] if 0 <= section < len(themes) else SectionTheme()
        # Create a new VisualIdentity with the section-specific theme merged in
        return VisualIdentity(
            description=vi.description,
            title_font=vi.title_font,
            body_font=vi.body_font,
            section_themes=[theme],  # Only pass the relevant theme
        )

    rng = random.Random(json.dumps(game_data, sort_keys=True))

    def _resolve_template(card: dict) -> str:
        if "template" in card:
            return card["template"]
        card_type = card.get("type", "")
        schema_cls = schema_by_type.get(card_type)
        if schema_cls:
            options = get_templates_for_schema(schema_cls)
            if options:
                return rng.choice(options).name
        raise ValueError(f"No template found for card type {card_type!r}")

    tasks = [
        (i, card, _resolve_template(card), _visual_identity_for_card(card))
        for i, card in enumerate(cards)
    ]

    results: list[Path] = Parallel(n_jobs=n_jobs, backend="threading")(
        delayed(render_card_to_pdf)(
            card,
            template_name,
            output_dir,
            images_dir,
            card_index=i,
            visual_identity=vi,
            runware_model=runware_model,
            force_regen_images=force_regen_images,
        )
        for i, card, template_name, vi in tasks
    )
    return results
